name: Linter and Build Workflow

on:
  push:
    branches:
      - finance
      - human-resources
      - sales
      - inventory
      - maintenance
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: removed node modules and package-lock.json
        run: |
          rm -rf node_modules
          rm -f package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
